apiVersion: v1
kind: Service

metadata:
  name: lb-svc
  labels:
    app: hello-app

spec:
    type: {{ .Values.service.type }}
    ports:
      - targetPort: {{ .Values.service.targetport }}
        port: {{ .Values.service.port }}
        nodePort: {{ .Values.service.nodeport }}
        protocol: TCP
    selector:
        app: hello-app
