apiVersion: v1
kind: Service

metadata:
  name: hello-svc

spec:
    type: NodePort
    ports:
      - targetPort: 8080
        port: 8080
        nodePort: 30080
    selector:
        name: hello-app
